services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
    - zookeeper_data:/var/lib/zookeeper/data
    - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - kafka_data:/var/lib/kafka/data

  mariadb:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    command:
      [
        "--server-id=1",
        "--log-bin=mysql-bin",
        "--binlog-format=ROW",
        "--binlog-row-image=FULL"
      ]
    volumes:
      - mariadb_data:/var/lib/mysql

  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: analytics
    secrets:
      - clickhouse_credentials
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - user_files:/var/lib/clickhouse/user_files
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -a
        . /run/secrets/clickhouse_credentials
        set +a
        exec /entrypoint.sh

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    platform: linux/amd64
    ports:
      - "8080:80"
    depends_on:
      - clickhouse

  debezium:
    image: debezium/connect:2.5
    depends_on:
      - kafka
      - mariadb
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - clickhouse
volumes:
  kafka_data:
  zookeeper_data:
  zookeeper_log:
  mariadb_data:
  clickhouse_data:
  user_files:
secrets:
  clickhouse_credentials:
    file: ./secrets/clickhouse_credentials.secret
